version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: 
          name: Node
          command: |
            node --version
            npm install
            npm run test