version: 2.1
jobs:
  node_test:
    executor: node:16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Run install
      - run:
          command: npm run test
          name: Run tests