import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Header.module.css'
import { parseCookies, setCookie, destroyCookie } from 'nookies'

export default function Header() {
  const cookies = parseCookies();

  return (
    <div>
      <Head>
        <title>オンレコ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        {/* ヘッダー左側 */}
        <Link href="/">
          <a className={styles.logo}>オンレコ</a>
        </Link>
        {/* ヘッダー右側 */}
          {cookies.token
            ?
            <p>ようこそ {cookies.name} さん&nbsp;&nbsp;</p>
            :
            <div>
            <Link href="/users/signup">
              <a className={styles.rightLogo}>新規登録</a>
            </Link>
            <Link href="/users/signin">
              <a className={styles.rightLogo}>ログイン</a>
            </Link>
          </div>
          }

      </header>
    </div>
  )
}