import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Header() {
  return (
    <div>
      <Head>
        <title>オンレコ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <Link href="/">
          <a className={styles.logo}>オンレコ</a>
        </Link>
      </header>
    </div>
  )
}