import Link from 'next/link'
import useSWR, { useSWRConfig } from 'swr'
import { useRouter } from 'next/router'
import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { apiURL } from '../unify/const'

export default function Detail() {
  const router = useRouter();

  // クエリパラメーターを取得する
  let { id } = router.query;
  // クエリパラメーターを取得できなかった場合は"false"という文字列を格納する
  if(!id){
    id = "false";
  }
  console.log("id---------------------------------------  " + id)
  // fetcher関数の第一引数にはuseSWRの第一引数が入る
  const fetcher = async (address: string) => {
    const res = await fetch(address);
    // もしステータスコードが 200-299 の範囲内では無い場合はエラーページに遷移する
    if (!res.ok) {
      router.push("/_error");
    }
  
    return res.json();
  }

  const { data, error } = useSWR(`${apiURL}/detail?id=${id}`, fetcher);

  // console.log("--------------------------" + JSON.stringify(data))
  // dataがない場合に戻り値を渡すと一瞬レイアウトが崩れる
  if(data){
    return (
      <div className={styles.container}>
        <Head>
          <title>オンレコ</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>詳細画面</h1>
        {data ? 
            <div>
              <ul>
              <h1>{data.ID}番</h1>
          <p>シチュエーション</p>
          <li>{data.Mst_situationName}</li>
          <p>曲名</p>
          <li>{data.Name}</li>
          <p>歌手名</p>
          <li>{data.Artist}</li>
          <p>おすすめポイント</p>
          <li>{data.Reason}</li>
          <p>投稿日</p>
          <li>{data.CreatedAt}</li>
              </ul>
            </div>
          :
            <p></p>
          }
        <Link href="/">
            <a>トップ画面へ戻る</a>
        </Link>
      </div>
    )
  }
}