import Head from 'next/head'

import styles from '../../styles/Home.module.css'

export default function Header() {
  return (
    <div>
      <Head>
        <title>オンレコ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <a href="/" className={styles.logo}>オンレコ</a>
      </header>
    </div>
  )
}